version: "3.8"

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    ports:
      - "8000:443"
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - catalogdb

  catalogdb:
    image: mcr.microsoft.com/mssql/server:2017-latest 
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - catalog-data:/var/opt/mssql/data
  
  store.api:
    image: ${DOCKER_REGISTRY-}storeapi
    ports:
      - "8001:443"
    build:
      context: .
      dockerfile: Services/Store/Store.API/Dockerfile
    depends_on:
      - storedb

  storedb:
    image: mcr.microsoft.com/mssql/server:2017-latest 
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1434:1433"
    volumes:
      - store-data:/var/opt/mssql/data

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    ports:
      - "8002:443"
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    depends_on:
     - orderingdb
     
  orderingdb:
    image: mcr.microsoft.com/mssql/server:2017-latest 
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1435:1433"
    volumes:
      - ordering-data:/var/opt/mssql/data

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    ports:
      - "8003:443"
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    depends_on:
     - basketdata

  basketdata:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - basketdata:/data

volumes:
  catalog-data:
  store-data:
  ordering-data:
  basketdata:
